version: '3.7'

services:
  # nginx:
  #   image: nginx:1.16.1
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./conf/nginx/local.crt:/var/www/ssl/local.crt
  #     - ./conf/nginx/local.key:/var/www/ssl/local.key
  #     - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./log/nginx:/var/log/nginx
  #     - ${PROJECT_PATH}:/var/www/html
  #   networks:
  #     - app

  # php:
  #   image: dylanops/php:7.4
  #   restart: always
  #   container_name: php
  #   volumes:
  #     - ./conf/php/php.ini:/usr/local/etc/php.ini
  #     - ./conf/php/xdebug:/usr/local/bin/xdebug
  #     - ./conf/php/opcache:/usr/local/bin/opcache
  #     - ${PROJECT_PATH}:/var/www/html
  #   networks:
  #     - app
  #   environment:
  #     PHP_IDE_CONFIG: 'serverName=web'
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: tubeedb
    volumes:
      # - ./conf/mysql/my.conf:/etc/mysql/my.cnf
      - ./data/backup:/var/backup
      - ./data/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     links:
       - mysql
     environment:
       PMA_HOST: mysql
       PMA_PORT: 3306
       PMA_ARBITRARY: 1
     ports:
       - "8081:80"
     networks:
       - app

  # elasticsearch:
  #   image: elasticsearch:7.13.2
  #   container_name: elasticsearch
  #   volumes:
  #     - ./data/es-data:/usr/share/elasticsearch/data
  #   ports:
  #     - "9300:9300"
  #     - "9200:9200"
  #   environment:
  #     discovery.type: single-node
  #   networks:
  #     - app
networks:
  app:
    driver: bridge
