version: '3.7'

services:

#  nginx:
#    image: nginx:1.21.6
#    container_name: nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./var/log/nginx:/var/log/nginx
#      - ${PROJECT_PATH}:/var/www/html
#    networks:
#      - app

  php:
    image: dylanops/php:8.1
    restart: always
    container_name: tubee-php
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - app
    environment:
      PHP_IDE_CONFIG: 'serverName=web'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb:10.7.4
    container_name: tubee-db
    volumes:
      - ./data/backup:/var/backup
      - ./data/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    container_name: tubee-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    networks:
      - app
networks:
  app:
    driver: bridge
